services:
  mock-server:
    build:
      context: ./mock-server
      dockerfile: Dockerfile
    ports:
      - "9002:9001"

  app:
    build:
      context: .
      dockerfile: Dockerfile_local
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      RHSSO_HOST: http://mock-server:9001
      HOST_API_CAIXA: http://mock-server:9001/
      AWS_ENDPOINT_URL: http://host.docker.internal:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      SQS_SALDO_URL: http://host.docker.internal:4566/000000000000/sqs-solic-protocolo-saldo
      SQS_CONSULTAR_PROTOCOLO_SALDO: http://host.docker.internal:4566/000000000000/sqs-res-saldo
      SQS_RESERVA_URL: http://host.docker.internal:4566/000000000000/sqs-res-reserva
      SQS_CONSULTAR_PROTOCOLO_RESERVA: http://host.docker.internal:4566/000000000000/sqs-res-reserva
    depends_on:
      - mock-server
