FROM 584539243974.dkr.ecr.sa-east-1.amazonaws.com/jenkins-agent-images:node-22.19.0-trixie AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM 584539243974.dkr.ecr.sa-east-1.amazonaws.com/digio/nodejs:dkr-app-node-22-latest1

USER root

WORKDIR /app

ENV NODE_ENV=production
ENV DT_ENV=none

COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

RUN set -eux; \
    chown -R node:node /app

USER node

EXPOSE 3000

CMD ["node", "dist/index.js"]