'use strict';

/**
 * Tabelas de códigos do Manual FGO (seção 14), extraídas do docs/FGO_MANUAL.txt.
 * As chaves são o valor numérico do código (ex.: "014" e "14" → 14).
 */

/** Códigos de rejeição da Remessa (§14.1). */
export const REJEICAO_REMESSA: Readonly<Record<number, string>> = {
  0: 'Remessa válida',
  1: 'Dado inválido no campo VERSÃO DO LEIAUTE',
  2: 'Arquivo vazio',
  3: 'Dado inválido no campo NÚMERO DO AGENTE FINANCEIRO',
  4: 'Dado inválido no campo CÓDIGO DO FUNDO GARANTIDOR',
  5: 'Dado inválido no campo NÚMERO SEQUENCIAL DA REMESSA',
  6: 'Dado inválido no campo NÚMERO SEQUENCIAL DO REGISTRO',
  7: 'Dado inválido no campo QUANTIDADE DE REGISTROS NO ARQUIVO',
  8: 'Versão de leiaute não permitida',
  9: 'Nome de arquivo remessa não permitido',
  10: 'Agente Financeiro não habilitado a operar com o Fundo',
  11: 'Agente Financeiro com pendência de movimentação financeira',
  12: 'Fundo Garantidor não habilitado a operar',
  13: 'Fundo Garantidor não cadastrado',
  14: 'Numeração da remessa fora de sequência',
  15: 'Numeração dos registros fora de sequência',
  16: 'Remessa com mais de um header',
  17: 'Primeiro registro não é header',
  18: 'Remessa sem registro trailer',
  19: 'Há registros após o trailer',
  20: 'Quantidade de registros da remessa difere da quantidade informada no trailer',
  21: 'Remessa entregue em data ou horário não permitido',
  23: 'Agente Financeiro não cadastrado',
  999: 'Remessa rejeitada por outro motivo (consulte o Administrador do Fundo)',
};

/** Códigos de rejeição dos registros (§14.2). */
export const REJEICAO_REGISTRO: Readonly<Record<number, string>> = {
  0: 'Dados válidos',
  1: 'TIPO DO REGISTRO inválido',
  2: 'Dado inválido no campo IDENTIFICADOR DA OPERAÇÃO',
  3: 'Dado inválido no campo NÚMERO DA AGÊNCIA',
  4: 'A data de formalização não pode ser futura',
  5: 'Dado inválido no campo CPF/CNPJ DO MUTUÁRIO',
  6: 'Dado inválido no campo FINALIDADE DO CRÉDITO',
  7: 'Dado inválido no campo MODALIDADE DO CRÉDITO',
  8: 'Dado inválido no campo DATA DA FORMALIZAÇÃO',
  9: 'Dado inválido no campo DATA PREVISTA DA PRIMEIRA LIBERAÇÃO',
  10: 'Dado inválido no campo VALOR PREVISTO DA PRIMEIRA LIBERAÇÃO',
  11: 'Dado inválido no campo TIPO DE PESSOA DO MUTUÁRIO',
  12: 'Dado inválido no campo DATA DE VENCIMENTO DA OPERAÇÃO',
  13: 'Dado inválido no campo VALOR DA OPERAÇÃO',
  14: 'Dado inválido no campo PERCENTUAL DE GARANTIA',
  15: 'Dado inválido no campo NOVO IDENTIFICADOR DA OPERAÇÃO',
  16: 'Faturamento superior ao máximo permitido',
  17: 'Dado inválido no campo SALDO DEVEDOR',
  18: 'A data do cancelamento não pode ser anterior a outro evento já informado',
  19: 'O saldo de capital não pode ser maior que o total liberado na operação',
  20: 'Saldo de capital maior que o valor da operação deduzido o valor da subvenção',
  21: 'Dado inválido no campo VALOR FINANCIADO ADICIONAL',
  22: 'Dado inválido no campo DATA DO SALDO',
  23: 'Dado inválido no campo SALDO DE CAPITAL EM NORMALIDADE',
  24: 'Dado inválido no campo SALDO DE CAPITAL EM ATRASO',
  25: 'Dado inválido no campo NÍVEL DE RISCO DA OPERAÇÃO',
  26: 'Dado inválido no campo DATA DA LIQUIDAÇÃO DA OPERAÇÃO',
  27: 'Dado inválido no campo DATA DE INÍCIO DA INADIMPLÊNCIA',
  28: 'Dado inválido no campo DATA DA SOLICITAÇÃO DE HONRA',
  29: 'Dado inválido no campo DATA DA RECUPERAÇÃO',
  30: 'Dado inválido no campo VALOR RECUPERADO',
  31: 'As datas informadas estão fora de uma ordem lógica entre si',
  32: 'Informou data futura em campo que exige data passada',
  33: 'Informou data passada em campo que exige data futura',
  34: 'Operação já cadastrada',
  35: 'Evento informado após o prazo limite',
  36: 'Procedimento não permitido para mutuário com operação honrada pelo Fundo Garantidor',
  37: 'Excedeu o valor máximo que pode ser garantido ao mutuário',
  38: 'Excedeu o valor máximo que pode ser garantido ao Agente Financeiro',
  39: 'O Fundo Garantidor atingiu o limite máximo de valores garantidos',
  40: 'Dados informados resultam em CCG igual a zero',
  41: 'Operação não cadastrada',
  42: 'Nenhuma alteração em relação aos dados já cadastrados',
  44: 'O Agente Financeiro excedeu o índice máximo de valores honrados',
  45: 'Já foi informado saldo com data mais recente que esta',
  46: 'Informou saldo em normalidade para operação vencida',
  48: 'A data de início da inadimplência não pode ser anterior à data de formalização',
  50: 'Não foi localizada a recuperação de valor honrado com os dados informados',
  51: 'Procedimento não permitido para operação na situação NORMALIDADE',
  52: 'Procedimento não permitido para operação na situação ATRASADA',
  53: 'Procedimento não permitido para operação na situação CANCELADA PELO AGENTE COM DEVOL CCG',
  54: 'Procedimento não permitido para operação na situação ENCERRADA PELO ADMINISTRADOR',
  55: 'Procedimento não permitido para operação na situação HONRADA',
  56: 'Procedimento não permitido para operação na situação LIQUIDADA APÓS A HONRA DA GARANTIA',
  57: 'Procedimento não permitido para operação na situação LIQUIDADA SEM HONRA DA GARANTIA',
  58: 'Dado inválido no campo SALDO BASE PARA CÁLCULO DO VALOR HONRADO',
  59: 'A data de início da inadimplência não confere com as informações de saldo anteriores',
  60: 'Período de inadimplência menor que o mínimo exigido',
  61: 'Período de inadimplência maior que o máximo permitido',
  62: 'Dado inválido no campo CÓDIGO IBGE DO MUNICÍPIO',
  64: 'Dado inválido no campo TIPO DE PÚBLICO-ALVO',
  65: 'Dado inválido no campo FATURAMENTO BRUTO ANUAL',
  66: 'Dado inválido no campo DATA DA LIBERAÇÃO',
  67: 'Dado inválido no campo VALOR DA LIBERAÇÃO',
  68: 'Dado inválido no campo VALOR DA CCG',
  69: 'Dado inválido no campo SALDO DE ENCARGOS EM NORMALIDADE',
  70: 'Dado inválido no campo SALDO DE ENCARGOS EM ATRASO',
  71: 'Mutuário já possui operação contratada/pré-validada no programa com este Agente Financeiro',
  72: 'A data do saldo não pode ser anterior à primeira liberação de crédito',
  88: 'Dado inválido no campo DATA DO CANCELAMENTO DA OPERAÇÃO',
  92: 'Valor garantido maior que o máximo permitido para a finalidade INVESTIMENTO',
  93: 'Valor garantido maior que o máximo permitido para a finalidade CAPITAL DE GIRO',
  94: 'Percentual de garantia menor que o mínimo exigido para a finalidade INVESTIMENTO',
  95: 'Percentual de garantia menor que o mínimo exigido para a finalidade CAPITAL DE GIRO',
  96: 'Percentual de garantia maior que o máximo permitido para a finalidade INVESTIMENTO',
  97: 'Percentual de garantia maior que o máximo permitido para a finalidade CAPITAL DE GIRO',
  100: 'Dado inválido no campo DATA DA ALTERAÇÃO DA OPERAÇÃO',
  103: 'O valor liberado somado com as liberações anteriores não pode superar o valor da operação',
  104: 'A CCG informada não confere com a CCG calculada pelo Administrador',
  107: 'Dado inválido no campo DATA DA RECUPERAÇÃO A CANCELAR',
  108: 'Procedimento não permitido para operação na situação IMPUGNADA',
  109: 'A data de liquidação não pode ser menor que a data do último evento informado',
  110: 'O Fundo Garantidor não permite este PÚBLICO-ALVO',
  113: 'Dado inválido no campo DATA DA REATIVAÇÃO DA OPERAÇÃO',
  114: 'Dado inválido no campo DATA DA DEVOLUÇÃO DO VALOR HONRADO',
  116: 'A data da devolução não pode ser anterior à data da honra da garantia',
  117: 'Procedimento não permitido para operação na situação FORMALIZADA',
  119: 'Procedimento não permitido para operação na situação CANCELADA PELO AGENTE',
  120: 'O valor liberado não pode ser maior que o valor da operação',
  121: 'Agente Financeiro não habilitado a operar com este Fundo Garantidor na data do evento',
  122: 'A data da liberação de crédito não pode ser maior que a data de vencimento da operação',
  123: 'A data da formalização não pode ser maior que a data de vencimento da operação',
  124: 'O valor da operação não pode ser menor que o seu saldo devedor',
  125: 'Dado inválido no campo DATA DO CANCELAMENTO DA RECUPERAÇÃO',
  126: 'Dado inválido no campo VALOR DA RECUPERAÇÃO A CANCELAR',
  127: 'A data da alteração não pode ser futura',
  128: 'Procedimento não permitido para operação com pendência',
  129: 'CPF/CNPJ inválido junto à Receita Federal do Brasil',
  130: 'Não deve ser cobrada CCG nesta liberação de crédito/ACP',
  131: 'Dado inválido no campo TIPO DE CRONOGRAMA DE AMORTIZAÇÃO',
  132: 'Dado inválido no campo CONDIÇÃO ESPECIAL DA OPERAÇÃO',
  133: 'Dado inválido no campo DATA PREVISTA DE VENCIMENTO DA OPERAÇÃO',
  134: 'A data de vencimento não pode ser alterada em operação com cronograma do tipo independente',
  135: 'Não permitido cronograma INDEPENDENTE para a modalidade/finalidade de crédito da operação',
  136: 'A data da liberação de crédito não pode ser anterior à data de formalização da operação',
  137: 'A data da liberação do crédito não pode ser futura',
  138: 'A data da reativação não pode ser anterior à data de liquidação da operação',
  139: 'A data da reativação não pode ser posterior à data de vencimento da operação',
  140: 'Dado inválido no campo DATA DO DESPACHO EXTERNO',
  142: 'Modalidade de crédito incompatível com a condição especial',
  143: 'Procedimento não permitido para operação na situação PARCELADA APÓS A HONRA DA GARANTIA',
  144: 'Dado inválido no campo DATA DO PARCELAMENTO',
  145: 'Dado inválido no campo VALOR DO SALDO PARCELADO',
  146: 'Dado inválido no campo DATA DE VENCIMENTO DO PARCELAMENTO',
  147: 'A data do parcelamento não pode ser anterior à data da honra da garantia',
  148: 'A data do parcelamento não pode ser futura',
  149: 'O saldo parcelado difere do saldo honrado a recuperar na data do parcelamento',
  150: 'A data de vencimento do parcelamento não pode ser anterior à data do parcelamento',
  151: 'Prazo de parcelamento maior que o máximo permitido',
  152: 'Dado inválido no campo FONTE DE RECURSOS',
  153: 'Dado inválido no campo PROGRAMA DE CRÉDITO',
  154: 'Prazo da operação maior que o máximo permitido',
  155: 'O código de público-alvo é incompatível com a condição especial',
  156: 'Data em dia não útil',
  157: 'O saldo não pode ser zero na enésima liberação em operação da modalidade CRÉDITO FIXO',
  158: 'A data do saldo deve ser o último dia do mês',
  159: 'A data do saldo não pode ser futura',
  160: 'A data da solicitação de honra não pode ser futura',
  161: 'A data do cancelamento não pode ser futura',
  162: 'A data da liquidação não pode ser futura',
  163: 'A data da reativação não pode ser futura',
  164: 'Tipo de condição especial não permitido nessa data de formalização',
  165: 'Tipo de condição especial não permitido nessa data de despacho externo',
  166: 'Saldo base incompatível com saldos anteriores da operação, conforme metodologia de cálculo',
  167: 'A data da alteração não pode ser anterior à data da formalização',
  168: 'O saldo devedor somado com o valor liberado não pode ser maior que o valor da operação',
  169: 'A data desta liberação de crédito não pode ser anterior à última informada',
  170: 'A data da liberação de crédito não pode ser anterior à data do despacho externo',
  171: 'A data do cancelamento não pode ser futura',
  172: 'Procedimento não permitido para mutuário com operação LIQUIDADA PÓS-HONRA COM ABATIMENTO',
  173: 'Procedimento não permitido para mutuário com operação CEDIDA PÓS-HONRA COM DESÁGIO',
  174: 'Dado inválido no campo VALOR DO ABATIMENTO',
  175: 'Dado inválido no campo TIPO DE ABATIMENTO',
  176: 'Procedimento não permitido para operação na situação LIQUIDADA PÓS-HONRA COM ABATIMENTO',
  177: 'Procedimento não permitido para operação na situação CEDIDA PÓS-HONRA COM DESÁGIO',
  178: 'Já existe operação formalizada com o identificador da operação substituta',
  179: 'A data da recuperação deve ser dia útil',
  180: 'A data da recuperação não pode ser anterior à data de solicitação da honra',
  181: 'A data da recuperação não pode ser futura',
  183: 'O valor do abatimento é incompatível com o tipo de abatimento',
  184: 'O prazo entre a solicitação de honra e o abatimento é menor que o permitido',
  185: 'Não cumpriu o prazo mínimo desde a solicitação de honra para fazer cessão com deságio',
  187: 'A recuperação a cancelar não foi a última informada',
  188: 'O saldo base informado resulta em valor honrado igual a zero',
  189: 'O código de público-alvo é incompatível com o tipo de pessoa',
  190: 'Dados informados na remessa divergem dos informados na pré-validação',
  192: 'Esta operação já foi pré-validada com reserva',
  193: 'Procedimento não permitido para mutuário com operação PARCELADA PÓS-HONRA',
  194: 'A operação original não foi liquidada',
  195: 'A data do cancelamento não pode ser anterior à data da recuperação a cancelar',
  196: 'Procedimento não permitido para operação que foi liquidada para novação de dívida',
  197: 'Código do tipo de formalização inválido',
  199: 'Não foi localizada a operação liquidada para a novação da dívida',
  200: 'O valor recuperado junto com o abatimento está abaixo do mínimo exigido',
  202: 'A data do abatimento não pode ser anterior a uma recuperação ou abatimento já informado',
  203: 'A data do abatimento não pode ser futura',
  204: 'A data do abatimento não pode ser anterior à data da honra da garantia',
  205: 'O prazo entre o início da inadimplência e o abatimento é menor que o permitido',
  206: 'Prazo entre os abatimentos é menor que o permitido',
  207: 'Já foi processado evento anterior que utilizou este número de reserva',
  208: 'A reserva expirou por decurso de prazo',
  209: 'A reserva foi cancelada pelo Agente Financeiro',
  210: 'Número de reserva não localizado',
  211: 'Dado inválido no campo NÚMERO DA RESERVA',
  212: 'Abatimento acima do percentual máximo permitido',
  213: 'O valor do abatimento não corresponde ao saldo honrado a recuperar',
  214: 'O valor do abatimento não pode ser maior nem igual ao saldo honrado',
  215: 'Dado inválido no campo DATA DO ABATIMENTO',
  216: 'O prazo entre a honra da garantia e o abatimento é menor que o permitido',
  217: 'Este tipo de evento não estava habilitado na data informada',
  218: 'Já foi processado evento de abatimento após a recuperação a cancelar',
  219: 'Não é permitido aumentar o valor da operação de novação',
  220: 'É proibida mais de uma liberação de crédito em operação do tipo "novação de dívida"',
  221: 'Prazo da operação menor que o mínimo permitido',
  222: 'Operação formalizada fora do período permitido',
  223: 'O valor da operação não pode ser alterado',
  224: 'A alteração da data de vencimento deve ser feita pelo evento 10',
  225: 'O valor liberado não pode ser zero',
  226: 'Empresa com mais de 1 ano de fundação deve informar faturamento maior que zero',
  227: 'Excedeu o valor máximo que pode ser financiado com base no faturamento do mutuário',
  228: 'Excedeu o valor máximo que pode ser financiado pelo Agente com a garantia desse Fundo',
  229: 'Tipo de evento não habilitado para este Fundo Garantidor',
  230: 'Excedeu o valor máximo que pode ser financiado a empresa com menos de 1 ano',
  231: 'Excedeu o valor máximo que pode ser financiado a cada mutuário',
  232: 'Excedeu o valor máximo que pode ser honrado pelo Fundo',
  233: 'Faturamento bruto anual inválido junto à RFB',
  234: 'Operação não cadastrada no SCR do BACEN',
  235: 'O faturamento informado anteriormente ainda está pendente de validação pela RFB',
  236: 'O faturamento informado anteriormente foi validado pela RFB',
  237: 'Operação pendente de validação no SCR do BACEN',
  238: 'Faturamento inferior ao mínimo permitido',
  239: 'A nova data de vencimento não pode ser anterior à originalmente formalizada',
  240: 'O Fundo Garantidor não permite este PROGRAMA DE CRÉDITO',
  241: 'Alteração de vencimento não permitida para esta operação',
  242: 'O prazo adicional, em relação ao vencimento original, é maior que o permitido',
  243: 'Relatório de auditoria externa não foi entregue ou está sem aceite do Administrador',
  244: 'O código de público-alvo é incompatível com o faturamento',
  245: 'Não permitido para operação formalizada em ano anterior',
  246: 'A alteração do programa de crédito não é permitida nesta operação',
  247: 'Evento não permitido para operação em processo de portabilidade na CIP',
  248: 'Procedimento não permitido para operação que já recuperou integralmente o saldo honrado',
  249: 'É obrigatório informar DATA INÍCIO INADIMPLÊNCIA quando há saldo de capital em atraso',
  250: 'Dado inválido no campo DATA INÍCIO DE INADIMPLÊNCIA',
  251: 'DATA DE INÍCIO DE INADIMPLÊNCIA menor que a informada anteriormente',
  252: 'DATA DE INÍCIO DE INADIMPLÊNCIA diferente da data informada no evento de saldo',
  253: 'Informou DATA DE INÍCIO DE INADIMPLÊNCIA, mas não há saldo de capital em atraso',
  254: 'TIPO DE MODALIDADE DE CRÉDITO não permitido',
  255: 'TIPO DE FINALIDADE DE CRÉDITO não permitido',
  256: 'Percentual de garantia menor que o mínimo exigido para a finalidade RENEGOCIAÇÃO',
  257: 'Percentual de garantia maior que o máximo permitido para a finalidade RENEGOCIAÇÃO',
  258: 'Alteração permitida somente para código identificador da operação',
  259: 'Dado inválido no campo VALOR DA SUBVENÇÃO',
  260: 'Este PROGRAMA DE CRÉDITO não permite subvenção',
  261: 'Valor ou percentual de subvenção não permitido',
  262: 'Mutuário já utilizou subvenção para este programa',
  263: 'O Agente atingiu seu limite máximo de subvenção neste PROGRAMA DE CRÉDITO',
  264: 'O Fundo atingiu o limite máximo de subvenção para este PÚBLICO-ALVO',
  265: 'Município não atendido por este programa de crédito.',
  266: 'O saldo de capital não pode ser maior que o valor da operação descontado o valor da subvenção',
  267: 'Para data de formalização futura, informar o próximo dia útil',
  268: 'A DATA DO SALDO informada não corresponde ao mês esperado',
  269: 'TIPO DE ABATIMENTO não permitido para este fundo garantidor',
  270: 'A data da primeira informação de saldo deve corresponder ao mês da primeira liberação de crédito',
  271: 'O saldo comprometido do mutuário excedeu o limite em relação ao seu faturamento',
  272: 'O saldo comprometido do mutuário excedeu o valor máximo permitido',
  273: 'O valor total financiado a este mutuário excedeu o limite por agente',
  274: 'Dado inválido no campo CPF QUALIFICADOR',
  275: 'CPF QUALIFICADOR não cadastrado na Receita Federal',
  276: 'O CPF QUALIFICADOR não tem gênero cadastrado na Receita Federal',
  277: 'O percentual de operações qualificadas como "mulher" na carteira do agente está abaixo do mínimo',
  278: 'O CPF QUALIFICADOR é diferente do CPF DO MUTUÁRIO',
  279: 'O saldo comprometido do mutuário excedeu o limite por fundos coligados',
  280: 'O saldo comprometido do mutuário excedeu o limite por agente',
  281: 'CPF QUALIFICADOR não cadastrado ou desatualizado no CadÚnico do Governo Federal',
  282: 'Não foi encontrado evento de honra para essa operação',
  283: 'Obrigatório informar Índice de Perda Esperada',
  284: 'Agente financeiro não habilitado a operar com subvenção',
  285: 'Município não habilitado a operar com subvenção',
  286: 'O PROGRAMA DE CRÉDITO não permite este TIPO DE PESSOA',
  287: 'O PROGRAMA DE CRÉDITO não permite este TIPO DE PÚBLICO-ALVO',
  288: 'O PROGRAMA DE CRÉDITO atingiu o limite máximo de subvenção',
  289: 'O PROGRAMA DE CRÉDITO atingiu o limite máximo de valores garantidos',
  290: 'Este PÚBLICO-ALVO atingiu o limite máximo de valores garantidos',
  291: 'O Agente atingiu seu limite máximo de subvenção para este PÚBLICO-ALVO',
  292: 'O Fundo atingiu o limite máximo de subvenção neste PROGRAMA DE CRÉDITO',
  293: 'A base de dados da Dataprev está indisponível para validar a região de calamidade pública',
  294: 'O mutuário não consta no cadastro de habilitados à subvenção da Dataprev',
  296: 'O mutuário e o município estão fora da região atendida por este Fundo Garantidor',
  297: 'O mutuário já contratou outra operação neste Fundo Garantidor',
  298: 'VALOR DA OPERAÇÃO acima do máximo permitido',
  300: 'Percentual de subvenção acima ou abaixo do permitido para este PROGRAMA DE CRÉDITO',
  302: 'Valor inválido no campo Índice de Perda Esperada',
  303: 'Informe valor válido em pelo menos um dos campos: NÍVEL DE RISCO ou ÍNDICE DE PERDA ESPERADA',
  304: 'Procedimento não permitido para operação na situação EXTINTA DE PLENO DIREITO',
  305: 'Procedimento não permitido para mutuário com operação EXTINTA DE PLENO DIREITO',
  306: 'Não cumpriu o prazo mínimo desde o vencimento da última parcela da operação',
  307: 'Ultrapassou o prazo máximo permitido para solicitação do abatimento',
  308: 'Saldo de encargos com valor desproporcional',
  312: 'Informação em duplicidade',
  313: 'Existe informação de saldo zerando o capital em atraso após a DATA DE INÍCIO DE INADIMPLÊNCIA',
  314: 'Não existe informação de saldo da operação no mês anterior à solicitação de honra',
  315: 'Procedimento não permitido para mutuário com operação honrada que recuperou menos de 30%',
  316: 'Dado inválido no campo VALOR CONDIÇÃO ESPECIAL',
  317: 'O Agente ultrapassou seu limite de contratação no programa de crédito',
  319: 'Procedimento não permitido para operação na situação SUSPENSA JUDICIALMENTE',
  320: 'CPF QUALIFICADOR não pode ser informado para operação formalizada nessa data',
  321: 'Esta operação não permite alterar o CÓDIGO IBGE DO MUNICÍPIO',
  323: 'Base de dados do Serpro indisponível para validar elegibilidade do mutuário ao programa',
  327: 'CNPJ/CPF não é beneficiário do programa, conforme regras vigentes.',
  328: 'VALOR DA RENEGOCIAÇÃO maior que o saldo devedor do mutuário',
  329: 'Operação fora do período de vigência da renegociação',
  330: 'FINALIDADE incompatível com a CONDIÇÃO ESPECIAL informada',
  331: 'Não existe operação pré-validada para o identificador da operação substituta informado',
  999: 'Registro rejeitado por outro motivo (consulte o Administrador)',
};

/** Tipo de pessoa (§14.3). */
export const TIPO_PESSOA: Readonly<Record<number, string>> = {
  1: 'Pessoa Física',
};

/** Público-alvo (§14.4). */
export const PUBLICO_ALVO: Readonly<Record<number, string>> = {
  7: 'Pessoa Física',
};

/** Modalidade de crédito (§14.5). */
export const MODALIDADE_CREDITO: Readonly<Record<number, string>> = {
  1: 'Crédito fixo',
};

/** Finalidade do crédito (§14.6). */
export const FINALIDADE_CREDITO: Readonly<Record<number, string>> = {
  1: 'Investimento',
  2: 'Capital de giro',
  3: 'Renegociação de dívida',
};

/** Fonte de recursos (§14.7). */
export const FONTE_RECURSOS: Readonly<Record<number, string>> = {
  11: 'Recurso próprio',
};

/** Programa de crédito (§14.8). */
export const PROGRAMA_CREDITO: Readonly<Record<number, string>> = {
  50: 'Novo Desenrola Brasil',
};

/** Tipo de cronograma de amortização (§14.9). */
export const TIPO_CRONOGRAMA: Readonly<Record<number, string>> = {
  1: 'Cronogramas unificados',
  2: 'Cronogramas independentes',
};

/** Condição especial da operação (§14.10). */
export const CONDICAO_ESPECIAL: Readonly<Record<number, string>> = {
  1: 'Sem condição especial',
};

/** Tipo de formalização (§14.11). */
export const TIPO_FORMALIZACAO: Readonly<Record<number, string>> = {
  1: 'Ordinária',
};

/** Tipo de pendência da operação (§14.12). */
export const TIPO_PENDENCIA: Readonly<Record<number, string>> = {
  1: 'Saldo devedor não informado pelo Agente',
  2: 'Operação de crédito fixo com saldo devedor zero',
  3: 'Operação vencida e com saldo em normalidade',
};

/** Motivo de encerramento da operação pelo Administrador (§14.13). */
export const MOTIVO_ENCERRAMENTO: Readonly<Record<number, string>> = {
  1: 'Saldo devedor não informado pelo Agente',
  2: 'Operação de crédito fixo com saldo devedor zero',
  3: 'Operação vencida e com saldo em normalidade ou sem liberação de crédito',
};

/** Situação da operação (§14.14). */
export const SITUACAO_OPERACAO: Readonly<Record<number, string>> = {
  1: 'Formalizada',
  2: 'Normalidade',
  3: 'Atrasada',
  4: 'Honrada',
  5: 'Liquidada pós-honra sem abatimento',
  6: 'Liquidada sem honra',
  7: 'Cancelada pelo Agente com devolução de CCG',
  8: 'Cancelada pelo Agente sem devolução de CCG',
  9: 'Encerrada pelo Administrador',
  10: 'Impugnada',
  11: 'Parcelada pós-honra',
  12: 'Liquidada pós-honra com abatimento',
  13: 'Cedida pós-honra com deságio',
  14: 'Extinta de pleno direito',
};

/** Motivo de impugnação da operação (§14.15). */
export const MOTIVO_IMPUGNACAO: Readonly<Record<number, string>> = {
  1: 'Operação contratada em desacordo com as normas',
  2: 'Honra de garantia solicitada em desacordo com as normas',
  3: 'Operação impugnada por outro motivo (consulte o Administrador do Fundo)',
};

/** Tipo de movimentação financeira (§14.16). */
export const TIPO_MOVIMENTACAO: Readonly<Record<number, string>> = {
  1: 'Recebimento de CCG',
  2: 'Devolução de CCG',
  3: 'Honra da garantia',
  4: 'Devolução de valor honrado',
  5: 'Recuperação de valor honrado',
  6: 'Devolução de valor recuperado',
  7: 'Abatimento no saldo honrado',
};

/** Natureza da movimentação financeira (§14.17). */
export const NATUREZA_MOVIMENTACAO: Readonly<Record<number, string>> = {
  1: 'A favor do FGO',
  2: 'A favor do Agente Financeiro',
  3: 'Sem movimentação',
};
